### ISSUE TITLE
main无法使用

### ISSUE THREAD

**Issue by nillin** [MisaLiu/BT-Server-Monitor#1]
按照教程来的，死活不对。服务器状态下面一直转圈。然后才发现demo是用another做的，瞬间崩溃。

**Comment by MisaLiu** [comment]
main 和 another 是独立的两个分支，请直接下载分支 clone，不要下载 release 以避免出现问题

另外可以提供一下 F12 下 Network 的报错截图吗？

**Comment by nillin** [comment]
![图片](https://user-images.githubusercontent.com/106225/127747721-9ab269cc-ecec-4067-b084-6b0790bbbbc0.png)
没说清楚是，是用main的教程来做的

**Comment by MisaLiu** [comment]
你可以尝试注释掉 `get.php` 头上的判定请求时间的代码

大概在 6~24行
