### ISSUE TITLE
搭建完成后，服务器状态页面一直转圈

### ISSUE THREAD

**Issue by chboy666** [MisaLiu/BT-Server-Monitor#2]
搭建完成后，服务器状态页面一直转圈

**Comment by MisaLiu** [comment]
请提供相关报错或是服务器响应截图

**Comment by chboy8** [comment]
页面没用任何报错，搭建网址：https://status.lli5.com/ 您帮忙看看

**Comment by chboy8** [comment]
PHP5.6-7.4均已测试，宝塔API已经开启且已加入白名单，问题并未解决。如果有需要，您可以将您的QQ发送给我吗？我将配置文件发送给您看看

**Comment by MisaLiu** [comment]
![image](https://user-images.githubusercontent.com/62408957/156810912-d9319d6f-8df8-4e91-a83a-e2f4e026844e.png)

请您在对应的目录手动新建一下文件夹（不用新建文件）

**Comment by chboy666** [comment]
请问我应该新建文件夹，文件夹如何命名呢？是新建至/wwwroot/tatus.lli5.com/吗？

**Comment by MisaLiu** [comment]
> 请问我应该新建文件夹，文件夹如何命名呢？是新建至/wwwroot/tatus.lli5.com/吗？

按照您设定的 cookie 目录进行新建即可

**Comment by chboy8** [comment]
您好，我已经新建文件夹至/data/qxcook/，打开网址还是一直转圈

**Comment by MisaLiu** [comment]
你好，已发布新的 Release，请尝试重新部署，如果还有问题可继续反馈
